### ISSUE TITLE
Doc improvement suggestion: Simple runnable examples

### ISSUE THREAD

**Issue by MasonProtter** [JuliaTesting/ReTest.jl#24]
This looks really interesting! In particular, when I read this line:

> 
> ReTest is a testing framework for Julia allowing:
> 
>  * Defining tests in source files, whose execution is deferred and triggered on demand.
> 
>  * This is useful when one likes to have definitions of methods and corresponding tests close to each other. This is also useful for code which is not (yet) organized as a package, and where one doesn't want to maintain a separate set of files for tests.

I got quite interested, but then reading further in the docs, I fas faced with a lot of quite verbose, technical documentation and no examples (that I could find) on how to actually do this or what it'd look like. 

A very simple, self contained, runnable example of defining a test next to a method near the beginning of the docs I think would be very helpful.

**Comment by rfourquet** [comment]
Thanks for the feedback! Can you have a look and review #25 ?
