### ISSUE TITLE
deprecation warnings from other packages pollutes the test log if running `pkg> test` using ReTest  

### ISSUE THREAD

**Issue by jonalm** [JuliaTesting/ReTest.jl#43]
Hi there,

Thanks for putting up ReTest, I love it.

One small issue I noticed: consider this minimal package https://github.com/jonalm/MyTestPackage.jl

When using `pkg> test`, the log output gets polluted by tons of deprecation warnings, like
```
WARNING: GeometryBasics.TRect is deprecated, use RectT instead.
  likely near none:1
WARNING: GeometryBasics.Vec1f0 is deprecated, use Vec1f instead.
  likely near none:1
WARNING: GeometryBasics.Vec2f0 is deprecated, use Vec2f instead.
  likely near none:1
 ....
```
which seems to originate here https://github.com/JuliaGeometry/GeometryBasics.jl/blob/master/src/deprecated.jl

These warning do not appear when using the normal Test package, and putting the testset in the `test/runtests.jl` file. However, when using ReTest from the command prompt, I do not see this issue

```julia
julia> using ReTest, MyTestPackage
julia> MyTestPackage.runtests()
        Pass
foo |      1
```

I originally reported this issue here https://github.com/JuliaGeometry/GeometryBasics.jl/issues/154 as I thought it was a GeometryBasics issue.

**Comment by rfourquet** [comment]
Thanks for your kind words, and very nice report with a reproducible example! This was fixed by #41, I will make a release later today.
